baseURL = 'https://erin-online.github.io'
languageCode = 'en-us'
title = 'im just vibing. im chilling and vibing on the internet'
theme = "terminal"

[params]

  themeColor = "pink"
  readingTime = true
  Toc = true
  Subtitle = 'le corner of the internet indie web site etc etc'
